//! The records the storage engine returns and the API lane serves.
//!
//! Every record is server-visible data only (AGENTS.md requirement 6): opaque
//! identifiers, ciphertext, sizes, timestamps, and graph shape. There is no
//! field for a path, a plaintext chunk, or an unwrapped key; `manifest_ct` is
//! ciphertext the server cannot read.
#![forbid(unsafe_code)]

use std::fmt;
use std::io;
use std::path::PathBuf;

use crate::types::{AccountId, DeviceId, DomainId, FileId, Seq, Sid, UnixMs, VersionId};

/// The single account this server holds (multi-account is a backlog issue).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AccountRecord {
    /// Account identifier, issued at setup.
    pub account_id: AccountId,
    /// Operator-chosen display name.
    pub name: String,
    /// When setup ran.
    pub created: UnixMs,
    /// Optional ceiling on stored ciphertext.
    pub quota_bytes: Option<u64>,
    /// Ciphertext bytes currently stored.
    pub used_bytes: u64,
}

/// Per-device upload ceilings, reported by the device and shown in the UI.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub struct DevicePolicy {
    /// Largest file this device will handle; `0` means unlimited.
    pub per_file_max_bytes: u64,
    /// Total bytes this device is willing to hold; `0` means unlimited.
    pub total_budget_bytes: u64,
}

/// Where a device is in its life (`docs/architecture.md` 4.2 and 4.3).
///
/// Three states and no fourth: a claimed device is `Pending` until the
/// pairing's creator approves it, `Active` once approved, and `Revoked`
/// once revoked. The record carries the state rather than a boolean, so
/// "approved but revoked" and "revoked but still pending" cannot be
/// written down at all (AGENTS.md requirement 4).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DeviceState {
    /// Claimed a pairing; holds a secret but no authority yet.
    Pending,
    /// Approved by the pairing's creator, or the first device at setup.
    Active,
    /// Revoked; its wrapped secret is destroyed and never comes back.
    Revoked,
}

impl DeviceState {
    /// The wire and journal word for this state.
    pub const fn as_word(self) -> &'static str {
        match self {
            DeviceState::Pending => "pending",
            DeviceState::Active => "active",
            DeviceState::Revoked => "revoked",
        }
    }

    /// Parse a wire word.
    pub fn parse(word: &str) -> Option<DeviceState> {
        match word {
            "pending" => Some(DeviceState::Pending),
            "active" => Some(DeviceState::Active),
            "revoked" => Some(DeviceState::Revoked),
            _ => None,
        }
    }
}

/// A paired device.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DeviceRecord {
    /// Device identifier issued at pairing.
    pub device_id: DeviceId,
    /// The account it belongs to.
    pub account_id: AccountId,
    /// User-chosen name.
    pub name: String,
    /// `ios`, `ipados`, `android`, `macos`, `windows` or `linux`.
    pub platform: String,
    /// Plugin version last reported.
    pub app_version: String,
    /// When the device was paired.
    pub created: UnixMs,
    /// Last authenticated request.
    pub last_seen: Option<UnixMs>,
    /// Last sign-in event.
    pub last_sign_in: Option<UnixMs>,
    /// Last version this device wrote.
    pub last_edit: Option<UnixMs>,
    /// Connecting address, as the edge or a trusted proxy reported it.
    pub address: Option<String>,
    /// Country, as the edge reported it.
    pub country: Option<String>,
    /// Reported ceilings.
    pub policy: DevicePolicy,
    /// Where the device is in its life.
    pub state: DeviceState,
}

impl DeviceRecord {
    /// Whether the device may authenticate a request that carries authority.
    pub fn active(&self) -> bool {
        self.state == DeviceState::Active
    }

    /// Whether the device is revoked; a revoked device authenticates never
    /// again. Kept as a predicate because the wire still states it as a
    /// boolean (`docs/protocol.md`, "Devices").
    pub fn revoked(&self) -> bool {
        self.state == DeviceState::Revoked
    }
}

/// A device to create. The secret is wrapped before it reaches the journal.
#[derive(Clone, Debug)]
pub struct NewDevice {
    /// The account it belongs to.
    pub account_id: AccountId,
    /// User-chosen name.
    pub name: String,
    /// Platform word.
    pub platform: String,
    /// Plugin version.
    pub app_version: String,
    /// The device secret, generated by the caller.
    pub secret: [u8; 32],
    /// The state the device starts in: `Active` for the first device at
    /// setup, `Pending` for a pairing claim awaiting approval.
    pub state: DeviceState,
}

/// What kind of activity a [`SeenEvent`] records.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SeenKind {
    /// The device signed in.
    SignIn,
    /// The device wrote a version.
    Edit,
    /// The device checked in.
    Heartbeat,
}

impl SeenKind {
    /// The wire word for this kind.
    pub const fn as_word(self) -> &'static str {
        match self {
            SeenKind::SignIn => "sign_in",
            SeenKind::Edit => "edit",
            SeenKind::Heartbeat => "heartbeat",
        }
    }

    /// Parse a wire word.
    pub fn parse(word: &str) -> Option<SeenKind> {
        match word {
            "sign_in" => Some(SeenKind::SignIn),
            "edit" => Some(SeenKind::Edit),
            "heartbeat" => Some(SeenKind::Heartbeat),
            _ => None,
        }
    }
}

/// One entry of a device's activity history, bounded by retention.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SeenEvent {
    /// What happened.
    pub kind: SeenKind,
    /// When it happened.
    pub ts: UnixMs,
    /// Connecting address, when one is known.
    pub address: Option<String>,
    /// Country, when one is known.
    pub country: Option<String>,
}

/// A stored version of a file.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VersionRecord {
    /// The file this version belongs to.
    pub file_id: FileId,
    /// The key-scoping domain the file is in, in clear
    /// (`docs/architecture.md` 5.1 item 4). A random id: it names no path and
    /// opens nothing, and it is what a per-domain grant will be checked
    /// against. Every version of a file repeats its file's domain; the store
    /// refuses one that does not.
    pub domain_id: DomainId,
    /// `SHA-256(file_id || sorted parents || manifest_ct || sids)`.
    pub version_id: VersionId,
    /// The versions this one supersedes.
    pub parents: Vec<VersionId>,
    /// The ciphertext chunks this version is assembled from, in order.
    pub sids: Vec<Sid>,
    /// Plaintext size the device declared.
    pub bytes: u64,
    /// The encrypted manifest. The server cannot read it.
    pub manifest_ct: Vec<u8>,
    /// The manifest's AES-GCM nonce.
    pub manifest_nonce: [u8; 12],
    /// The device that wrote it.
    pub device_id: DeviceId,
    /// When the server accepted it.
    pub ts: UnixMs,
    /// Whether this version is a tombstone.
    pub deleted: bool,
    /// Journal position, the change feed's cursor.
    pub seq: Seq,
}

/// A version to append.
#[derive(Clone, Debug)]
pub struct NewVersion {
    /// The account it belongs to.
    pub account_id: AccountId,
    /// The file.
    pub file_id: FileId,
    /// The domain the device says the file is in. Fixed by the file's first
    /// version; a later version naming another domain is refused.
    pub domain_id: DomainId,
    /// The version id the device computed; the server recomputes and compares.
    pub version_id: VersionId,
    /// The versions this one supersedes.
    pub parents: Vec<VersionId>,
    /// The chunks, in order.
    pub sids: Vec<Sid>,
    /// Plaintext size.
    pub bytes: u64,
    /// The encrypted manifest.
    pub manifest_ct: Vec<u8>,
    /// The manifest's nonce.
    pub manifest_nonce: [u8; 12],
    /// The authoring device.
    pub device_id: DeviceId,
    /// Whether this is a tombstone.
    pub deleted: bool,
}

/// A file with its heads and its retained versions, newest first.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FileRecord {
    /// The file.
    pub file_id: FileId,
    /// The domain this file is in, set by its first version and immutable.
    pub domain_id: DomainId,
    /// Current heads: one when the file agrees, more when it conflicts.
    pub heads: Vec<VersionId>,
    /// Whether the file has more than one head.
    pub conflicted: bool,
    /// Retained versions, newest first, plus every head.
    pub versions: Vec<VersionRecord>,
}

/// One line of the file listing.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FileSummary {
    /// The file.
    pub file_id: FileId,
    /// The domain this file is in.
    pub domain_id: DomainId,
    /// Current heads.
    pub heads: Vec<VersionId>,
    /// Whether the file has more than one head.
    pub conflicted: bool,
    /// Timestamp of the newest version.
    pub latest_ts: UnixMs,
}

/// One entry of the change feed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Change {
    /// The version that landed.
    pub version: VersionRecord,
    /// The file's heads as they stand now.
    pub heads: Vec<VersionId>,
    /// Whether the file conflicts now.
    pub conflicted: bool,
}

/// A page of the change feed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Changes {
    /// The last sequence this page covers.
    pub seq: Seq,
    /// The journal head at the time of the read.
    pub head_seq: Seq,
    /// The changes, in sequence order.
    pub changes: Vec<Change>,
}

/// One volume's usage against its declared capacity.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VolumeStatus {
    /// `blobs`, `journal` or `mirror`.
    pub role: String,
    /// Where it is mounted.
    pub path: PathBuf,
    /// Display label for the volume's class, from `OBSYNC_*_CLASS`; the
    /// dashboard shows this and never the path.
    pub class_label: String,
    /// Declared capacity (`OBSYNC_*_CAPACITY`).
    pub bytes_total: u64,
    /// Bytes tracked as used.
    pub bytes_used: u64,
    /// Capacity minus usage.
    pub bytes_free: u64,
    /// The refusal threshold for this volume.
    pub watermark_bytes: u64,
}

/// The result of one garbage-collection run.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GcSummary {
    /// When the run started.
    pub started: UnixMs,
    /// How long it took.
    pub duration_ms: u64,
    /// Chunks deleted.
    pub chunks_collected: u64,
    /// Bytes reclaimed.
    pub bytes_collected: u64,
    /// Chunks still referenced.
    pub chunks_retained: u64,
}

/// The result of one scrub step.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ScrubSummary {
    /// When the step started.
    pub started: UnixMs,
    /// How long it took.
    pub duration_ms: u64,
    /// Chunks re-hashed.
    pub chunks_verified: u64,
    /// Bytes re-hashed.
    pub bytes_verified: u64,
    /// Chunks whose content did not match their sid.
    pub mismatches: u64,
    /// Mismatches that no mirror could repair; moved to `quarantine/`.
    pub quarantined: Vec<Sid>,
    /// Whether this step finished a full pass over the volume.
    pub complete_pass: bool,
}

/// Whether a chunk upload created a chunk or found it already stored.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PutOutcome {
    /// The chunk is new; the response is `201`.
    Created,
    /// The chunk was already stored; the response is `200`.
    Existed,
}

/// What appending a version did.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AppendOutcome {
    /// The journal position of the version.
    pub seq: Seq,
    /// The file's heads afterwards.
    pub heads: Vec<VersionId>,
    /// Whether the file conflicts afterwards.
    pub conflicted: bool,
    /// Whether this version was already stored (an idempotent repost).
    pub existed: bool,
}

/// Every way the storage engine refuses or fails.
///
/// Each variant carries the numbers the refusal was decided on, so the log
/// line and the HTTP body can both state them (AGENTS.md requirement 12).
#[derive(Debug)]
pub enum StoreError {
    /// The body did not hash to the sid it was stored under.
    SidMismatch {
        /// The sid the client asked for.
        expected: Sid,
        /// The sid the body actually hashes to.
        actual: Sid,
    },
    /// The body length did not match `Content-Length`.
    LengthMismatch {
        /// What the client declared.
        declared: u64,
        /// What arrived.
        actual: u64,
    },
    /// Free space is at or below the watermark.
    VolumeFull {
        /// Bytes free after this write would land.
        free: u64,
        /// The refusal threshold.
        watermark: u64,
    },
    /// The account quota is exhausted.
    QuotaExceeded {
        /// Bytes used after this write would land.
        used: u64,
        /// The quota.
        quota: u64,
    },
    /// A version referenced chunks the server does not hold.
    MissingChunks(Vec<Sid>),
    /// The posted version id is not the server's recomputation.
    VersionIdMismatch {
        /// What the server computed.
        expected: VersionId,
        /// What the client posted.
        actual: VersionId,
    },
    /// A feed cursor beyond the journal head.
    SeqAhead {
        /// What the client asked for.
        requested: Seq,
        /// The journal head.
        head: Seq,
    },
    /// No such device.
    UnknownDevice,
    /// The device is revoked.
    DeviceRevoked,
    /// The device claimed a pairing but nobody has approved it.
    DevicePending,
    /// No such file.
    UnknownFile,
    /// No such domain: no file the store holds is in it.
    UnknownDomain,
    /// A version named a domain other than its file's own.
    DomainMismatch {
        /// The domain the file's first version fixed.
        expected: DomainId,
        /// What this version named.
        actual: DomainId,
    },
    /// No such version.
    UnknownVersion,
    /// Setup has not run.
    NotSetUp,
    /// Setup has already run.
    AlreadySetUp,
    /// The filesystem refused.
    Io(io::Error),
    /// A volume root or credential file whose type, owner, or mode is not
    /// safe to serve from, and could not be corrected.
    Posture {
        /// Which class of path, matching the refusal line's `path_class`.
        class: &'static str,
        /// Why it was refused, matching the refusal line's `reason`.
        reason: &'static str,
    },
    /// On-disk state that replay cannot make sense of.
    Corrupt(String),
}

impl fmt::Display for StoreError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            StoreError::SidMismatch { expected, actual } => {
                write!(
                    f,
                    "sid mismatch: expected {expected}, body hashes to {actual}"
                )
            }
            StoreError::LengthMismatch { declared, actual } => {
                write!(f, "length mismatch: declared {declared}, received {actual}")
            }
            StoreError::VolumeFull { free, watermark } => {
                write!(f, "volume full: {free} bytes free, watermark {watermark}")
            }
            StoreError::QuotaExceeded { used, quota } => {
                write!(f, "quota exceeded: {used} bytes used, quota {quota}")
            }
            StoreError::MissingChunks(sids) => write!(f, "missing {} chunks", sids.len()),
            StoreError::VersionIdMismatch { expected, actual } => {
                write!(
                    f,
                    "version id mismatch: expected {expected}, posted {actual}"
                )
            }
            StoreError::SeqAhead { requested, head } => {
                write!(f, "seq {requested} is ahead of head {head}")
            }
            StoreError::UnknownDevice => f.write_str("unknown device"),
            StoreError::DeviceRevoked => f.write_str("device revoked"),
            StoreError::DevicePending => f.write_str("device pending approval"),
            StoreError::UnknownFile => f.write_str("unknown file"),
            StoreError::UnknownDomain => f.write_str("unknown domain"),
            StoreError::DomainMismatch { expected, actual } => {
                write!(
                    f,
                    "domain mismatch: file is in {expected}, version named {actual}"
                )
            }
            StoreError::UnknownVersion => f.write_str("unknown version"),
            StoreError::NotSetUp => f.write_str("not set up"),
            StoreError::AlreadySetUp => f.write_str("already set up"),
            StoreError::Io(e) => write!(f, "io error: {:?}", e.kind()),
            StoreError::Posture { class, reason } => {
                write!(f, "unsafe posture on the {class}: {reason}")
            }
            StoreError::Corrupt(what) => write!(f, "corrupt on-disk state: {what}"),
        }
    }
}

impl std::error::Error for StoreError {}

impl From<io::Error> for StoreError {
    fn from(e: io::Error) -> StoreError {
        StoreError::Io(e)
    }
}

impl StoreError {
    /// The snake_case refusal code for this error (`docs/protocol.md`).
    ///
    /// A `&'static str`, so it can be logged without carrying runtime data.
    pub const fn code(&self) -> &'static str {
        match self {
            StoreError::SidMismatch { .. } => "sid_mismatch",
            StoreError::LengthMismatch { .. } => "length_mismatch",
            StoreError::VolumeFull { .. } => "volume_full",
            StoreError::QuotaExceeded { .. } => "quota_exceeded",
            StoreError::MissingChunks(_) => "missing_chunks",
            StoreError::VersionIdMismatch { .. } => "version_id_mismatch",
            StoreError::SeqAhead { .. } => "seq_ahead",
            StoreError::UnknownDevice => "unknown_device",
            StoreError::DeviceRevoked => "device_revoked",
            StoreError::DevicePending => "device_pending",
            StoreError::UnknownFile => "unknown_file",
            StoreError::UnknownDomain => "unknown_domain",
            StoreError::DomainMismatch { .. } => "domain_mismatch",
            StoreError::UnknownVersion => "unknown_version",
            StoreError::NotSetUp => "not_set_up",
            StoreError::AlreadySetUp => "already_set_up",
            StoreError::Io(_) => "io_error",
            StoreError::Posture { .. } => "unsafe_posture",
            StoreError::Corrupt(_) => "corrupt",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn refusals_state_their_numbers_and_a_stable_code() {
        let err = StoreError::VolumeFull {
            free: 7,
            watermark: 2048,
        };
        assert_eq!(err.to_string(), "volume full: 7 bytes free, watermark 2048");
        assert_eq!(err.code(), "volume_full");

        let err = StoreError::QuotaExceeded { used: 10, quota: 5 };
        assert_eq!(err.to_string(), "quota exceeded: 10 bytes used, quota 5");
        assert_eq!(err.code(), "quota_exceeded");

        let err = StoreError::LengthMismatch {
            declared: 4,
            actual: 5,
        };
        assert_eq!(err.to_string(), "length mismatch: declared 4, received 5");
        assert_eq!(err.code(), "length_mismatch");

        let err = StoreError::SeqAhead {
            requested: Seq(9),
            head: Seq(3),
        };
        assert_eq!(err.to_string(), "seq 9 is ahead of head 3");
        assert_eq!(err.code(), "seq_ahead");

        // A posture refusal states the class and the reason, both compile
        // time words, and no location.
        let err = StoreError::Posture {
            class: "server_key",
            reason: "symlink",
        };
        assert_eq!(err.to_string(), "unsafe posture on the server_key: symlink");
        assert_eq!(err.code(), "unsafe_posture");
    }

    #[test]
    fn io_errors_never_render_their_message() {
        let err = StoreError::from(io::Error::new(
            io::ErrorKind::PermissionDenied,
            "/data/blobs/v1/aa/bb/secret",
        ));
        let text = err.to_string();
        assert!(!text.contains("/data"), "{text}");
        assert_eq!(text, "io error: PermissionDenied");
        assert_eq!(err.code(), "io_error");
    }

    #[test]
    fn device_states_round_trip_their_wire_words() {
        for state in [
            DeviceState::Pending,
            DeviceState::Active,
            DeviceState::Revoked,
        ] {
            assert_eq!(DeviceState::parse(state.as_word()), Some(state));
        }
        assert_eq!(DeviceState::parse("approved"), None);
        assert_eq!(DeviceState::parse(""), None);
    }

    #[test]
    fn seen_kinds_round_trip_their_wire_words() {
        for kind in [SeenKind::SignIn, SeenKind::Edit, SeenKind::Heartbeat] {
            assert_eq!(SeenKind::parse(kind.as_word()), Some(kind));
        }
        assert_eq!(SeenKind::parse("deleted"), None);
    }
}
