import { CATALOG, UNSUPPORTED } from './catalog.mjs';

const lines = ['# Offline CLI command reference', '',
  'Generated by `node cli/reference.mjs` from the shared operation catalog.', '',
  'This source candidate is not a published installation.', '',
  '| Operation | Command | Effect | Result |', '| --- | --- | --- | --- |'];
for (const entry of CATALOG) {
  lines.push(`| \`${entry.operation}\` | \`${entry.command}\` | ${entry.effect} | ${entry.summary} |`);
}
lines.push('', 'Inspect `schema OPERATION` for inputs, output envelope, bounds, retry rules and examples.', '',
  '## Unsupported families', '');
for (const [name, reason] of Object.entries(UNSUPPORTED)) lines.push(`- \`${name}\`: ${reason}`);
process.stdout.write(`${lines.join('\n')}\n`);
