/**
 * The obsync plugin bundler. Node built-ins only — no bundler package, no
 * plugin ecosystem, nothing to audit but this file (AGENTS.md requirement 5).
 *
 * `tsc` emits one CommonJS file per module under `build/`. This wraps each
 * one in a factory inside a tiny registry and concatenates them into a single
 * `dist/main.js`, which is what Obsidian loads. `require("obsidian")` — and
 * `require("fs")` on desktop — fall through to the real `require`, because
 * the host provides them.
 *
 * The output is deterministic: modules are emitted in sorted order and no
 * timestamp, path or environment value is written into the bundle, so the
 * same commit always produces the same SHA-256. The release evidence
 * manifest depends on that.
 *
 * Usage: `node build.mjs` (after `tsc -p tsconfig.json`), or `npm run build`.
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const buildDir = join(root, "build");
const distDir = join(root, "dist");

async function jsFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await jsFiles(full)));
    else if (entry.name.endsWith(".js")) found.push(full);
  }
  return found;
}

function moduleId(file) {
  return `./${relative(buildDir, file).split(/[\\/]/).join("/").replace(/\.js$/, "")}`;
}

const runtime = `// obsync plugin bundle. Generated by plugin/build.mjs from plugin/src.
// One CommonJS module registry, no dependencies, no bundler.
"use strict";
var __cache = {};
function __resolve(from, id) {
  if (id.charAt(0) !== ".") return id;
  var parts = (from.slice(0, from.lastIndexOf("/")) + "/" + id).split("/");
  var out = [];
  for (var i = 0; i < parts.length; i++) {
    if (parts[i] === "" || parts[i] === ".") continue;
    if (parts[i] === "..") out.pop();
    else out.push(parts[i]);
  }
  return "./" + out.join("/");
}
function __load(id) {
  if (__cache[id]) return __cache[id].exports;
  var factory = __modules[id];
  if (!factory) return require(id);
  var mod = { exports: {} };
  __cache[id] = mod;
  factory(mod, mod.exports, function (child) {
    return __load(__resolve(id, child));
  });
  return mod.exports;
}
`;

async function main() {
  const files = (await jsFiles(buildDir)).sort();
  if (files.length === 0) throw new Error("build.mjs: build/ is empty — run tsc first");

  const parts = ["var __modules = {};\n"];
  for (const file of files) {
    const id = moduleId(file);
    const code = await readFile(file, "utf8");
    parts.push(`__modules[${JSON.stringify(id)}] = function (module, exports, require) {\n${code}};\n`);
  }
  const bundle = `${runtime}${parts.join("")}module.exports = __load("./main").default;\n`;

  await rm(distDir, { recursive: true, force: true });
  await mkdir(distDir, { recursive: true });
  await writeFile(join(distDir, "main.js"), bundle);
  await writeFile(join(distDir, "manifest.json"), await readFile(join(root, "manifest.json")));
  await writeFile(join(distDir, "styles.css"), await readFile(join(root, "styles.css")));

  for (const name of ["main.js", "manifest.json", "styles.css"]) {
    const bytes = await readFile(join(distDir, name));
    const hash = createHash("sha256").update(bytes).digest("hex");
    console.log(`${name} bytes=${bytes.length} sha256=${hash}`);
  }
  console.log(`modules=${files.length}`);
}

await main();
